### ISSUE TITLE
Memory Increment

### ISSUE THREAD

**Issue by rnc** [apheleia-project/jbs-build-issues#8]
When building micrometer (after applying the fix in #7) I am seeing `OOMKilled` in the pods.

Assuming I'm looking at the correct yaml I see:
```
  containers:
    - resources:
        limits:
          cpu: 300m
          memory: 1Gi
        requests:
          cpu: 300m
          memory: 1Gi
      terminationMessagePath: /tekton/termination
      name: step-build
```
for *both* 51aa01903a6cdeb5e503c189c1ad98e9-build-0-build-pod and 51aa01903a6cdeb5e503c189c1ad98e9-build-1-build-pod (while 51aa01903a6cdeb5e503c189c1ad98e9-build-2-build-pod has 2GB).

@stuartwdouglas Shouldn't there be an increment between the first two builds?
